Finishes Docker refactoring (#3238)
This does several things of importance around Docker:

* Makes default heap for 'mem' 128m, slim 32m and otherwise 64m
  * We now use `-XX:+ExitOnOutOfMemoryError` instead of letting the process live on OOM
  * Before, memory was unbounded
* Consolidates zipkin production images similar to zipkin-dependencies:
  * See https://github.com/openzipkin/zipkin-dependencies/pull/181
  * This means no duplicated Dockerfile
* Removes detection of legacy docker links and associated profiles
  * these were added for an old docker-compose setup
  * added a README example for the ancient
* Makes ENTRYPOINT and HEALTHCHECK like other images
* Changes example to suggest applying logging via `command` not `JAVA_OPTS`
* Switches docker-compose examples to use imports
* Adds docker-compose-example.xml
* Consolidates RATIONALE
* Switches to GitHub actions to test images

diff --git a/docker/bin/docker-healthcheck b/docker/bin/docker-healthcheck
--- a/docker/bin/docker-healthcheck
+++ b/docker/bin/docker-healthcheck
@@ -1,3 +1,4 @@
+#!/bin/sh
 #
 # Copyright 2015-2020 The OpenZipkin Authors
 #
@@ -12,22 +13,21 @@
 # the License.
 #
 
-# This file uses the version 2 docker-compose file format, described here:
-# https://docs.docker.com/compose/compose-file/#version-2
-#
-# It extends the default configuration from docker-compose.yml, hosting the
-# ui on port 80 using NGINX
+# HEALTHCHECK for use in `docker ps` or `docker-compose ps`.
+# It can also be used as a readiness probe in k8s
 
-version: '2.4'
+# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
+set -u +e
 
-services:
-  zipkin-ui:
-    image: openzipkin/zipkin-ui:${TAG:-latest}
-    container_name: zipkin-ui
-    environment:
-      # Change this if connecting to a different zipkin server
-      - ZIPKIN_BASE_URL=http://zipkin:9411
-    ports:
-      - 80:80
-    depends_on:
-      - zipkin
+IP="$(hostname -i || echo '127.0.0.1')"
+PORT=${QUERY_PORT:-9411}
+
+# Use b3:0 to ensure health checks aren't traced
+HEALTH_OUT=$(wget -qO- http://${IP}:${PORT} --header=b3:0 2>&1)
+HEALTH_RC=$?
+if [ "$HEALTH_RC" == "0" ]; then
+  exit 0
+fi
+
+echo health check failed with code $HEALTH_RC response: ${HEALTH_OUT}
+exit 1
diff --git a/docker/lens/docker-bin/docker-healthcheck b/docker/lens/docker-bin/docker-healthcheck
--- a/docker/lens/docker-bin/docker-healthcheck
+++ b/docker/lens/docker-bin/docker-healthcheck
@@ -13,14 +13,20 @@
 # the License.
 #
 
-if [ -f ".${STORAGE_TYPE}_profile" ]; then
-  source ${PWD}/.${STORAGE_TYPE}_profile
+# HEALTHCHECK for use in `docker ps` or `docker-compose ps`.
+# It can also be used as a readiness probe in k8s
+
+# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
+set -u +e
+
+IP="$(hostname -i || echo '127.0.0.1')"
+
+# Use b3:0 to ensure health checks aren't traced
+HEALTH_OUT=$(wget -qO- http://${IP}/health --header=b3:0 2>&1)
+HEALTH_RC=$?
+if [ "$HEALTH_RC" == "0" ]; then
+  exit 0
 fi
 
-# Use main class directly if there are no modules, as it measured 14% faster from JVM running to available
-# verses PropertiesLauncher when using Zipkin was based on Spring Boot 2.1
-if [[ -z "$MODULE_OPTS" ]]; then
-  exec java ${JAVA_OPTS} -cp '.:BOOT-INF/lib/*:BOOT-INF/classes' zipkin.server.ZipkinServer
-else
-  exec java ${MODULE_OPTS} ${JAVA_OPTS} -cp . org.springframework.boot.loader.PropertiesLauncher
-fi
+echo health check failed with code $HEALTH_RC response: ${HEALTH_OUT}
+exit 1
