Moves to GitHub actions build (#3311)
On CI:
  * Travis is still cutoff despite over a week of email.
  * We have to switch to GitHub actions to avoid paralyzing the project

On docker images:
  * zipkin-mysql and zipkin-ui now FROM openzipkin/alpine image, to ensure architectures like amd64 are uniform.
  * test images are reorganized under [docker/test-images] to help understand what's production or not.
  * [build-bin/docker_push] pushes test-images, but only to ghcr.io

On [build-bin]
  * [build-bin] largely reuses scripts used in other projects like zipkin-storage-kafka
  * This is discussed in [build-bin/README.md]


[zipkin-lens] is a node.js project, which has some additional concerns
* [build-bin/maybe_install_npm] is used to build on an unsupported node.js architecture.
* [build-bin/maven_go_offline] additionally seeds the NPM cache

On test:
* [build-bin/test], used by [.github/workflows/test.yml] runs Maven unit and integration tests.
* [.github/workflows/readme_test.yml] tests build commands in [zipkin-server] and [docker]
* zipkin, zipkin-lens and zipkin-slim Docker builds use `RELEASE_FROM_MAVEN_BUILD=true`
  * this avoids invoking Maven builds from within Docker, which are costly and fragile

On deploy:
* [build-bin/javadoc_to_gh_pages] pushes Javadoc to the gh-pages branch on N.M.L branch, but not master.

diff --git a/build-bin/javadoc_to_gh_pages b/build-bin/javadoc_to_gh_pages
--- a/build-bin/javadoc_to_gh_pages
+++ b/build-bin/javadoc_to_gh_pages
@@ -15,18 +15,24 @@
 
 set -ue
 
-# This script creates JavaDoc for a version and pushes an update to gh-pages
-version=$1
+# This script creates JavaDoc for a version and pushes an update to gh-pages. This fails if there
+# are no javadoc jars in the current directory.
+#
+# This leaves the git context on gh-pages when done. For this reason, it is better to run this at
+# the end of deployment.
+version=${1?version is required. Ex 2.22.2}
+
 rm -rf javadoc-builddir
-builddir="javadoc-builddir/$version"
+builddir="javadoc-builddir/${version}"
 
-git checkout $version
-
-# Need to use compile in order for sibling modules to see each-other
-./mvnw -Prelease clean compile javadoc:javadoc
+javadoc_jars=$(find . -name "*${version}-javadoc.jar")
+if [ -z "${javadoc_jars}"]; then
+  >&2 echo Incorrect state. javadoc jars should have been built before invoking this.
+  exit 1
+fi
 
 # Collect javadoc for all modules
-for jar in $(find . -name "*${version}-javadoc.jar"); do
+for jar in ${javadoc_jars}; do
   module="$(echo "$jar" | sed "s~.*/\(.*\)-${version}-javadoc.jar~\1~")"
   this_builddir="$builddir/$module"
   if [ -d "$this_builddir" ]; then
@@ -44,12 +50,12 @@ done
 # Update gh-pages
 git fetch origin gh-pages:gh-pages
 git checkout gh-pages
-rm -rf "$version"
-mv "javadoc-builddir/$version" ./
+rm -rf "${version}"
+mv "javadoc-builddir/${version}" ./
 rm -rf "javadoc-builddir"
 
 # Update simple version-level index
-if ! grep "$version" index.html 2>/dev/null; then
+if ! grep "${version}" index.html 2>/dev/null; then
   echo "<li><a href=\"${version}/index.html\">${version}</a></li>" >> index.html
 fi
 
@@ -57,7 +63,7 @@ fi
 sort -rV index.html > index.html.sorted
 mv index.html.sorted index.html
 
-git add "$version"
+git add "${version}"
 git add index.html
-git commit -m "Automatically updated javadocs for $version"
+git commit -m "Automatically updated javadocs for ${version}"
 git push origin gh-pages
